Switch to regular role
AbsaOSS/terraform-controller pull request #40
Opened 2021-06-01 20:51 UTC by k0da

Controller runs under regular role now, it can't excalate priveleges
during SA creation for execution.

Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>

2021-06-01 21:33 UTC, somaritane commented on pkg/terraform/state/deploy.go
> +		logrus.Errorf("error creating crb for %s top level %v", state.Name, err)
```suggestion
		logrus.Errorf("error creating role for %s top level %v", state.Name, err)
```

2021-06-01 21:34 UTC, somaritane commented on pkg/terraform/state/deploy.go
>  		logrus.Errorf("error creating crb for %s top level %v", state.Name, err)
```suggestion
		logrus.Errorf("error creating RoleBinding for %s top level %v", state.Name, err)
```

2021-06-02 09:29 UTC, somaritane requested changes

2021-06-02 09:29 UTC, somaritane commented on pkg/terraform/state/deploy.go
>  		Name:            "crb-" + name,
```suggestion
		Name:            "rb-" + name,
```

2021-06-02 18:29 UTC, k0da commented
@somaritane e2e passing. It also covers state delete (terraform destroy) case

2021-06-02 21:50 UTC, somaritane commented
> @somaritane e2e passing. It also covers state delete (terraform destroy) case

@k0da , unfortunately, state deletion doesn't work on my e2e environment, no destroy execution is started when the state is deleted.

2021-06-02 21:53 UTC, k0da commented
@somaritane this test passes https://github.com/AbsaOSS/terraform-controller/blob/master/e2e/e2e_test.go#L190

2021-06-02 22:10 UTC, somaritane commented
> @somaritane this test passes https://github.com/AbsaOSS/terraform-controller/blob/master/e2e/e2e_test.go#L190

@k0da , my bad, I had the `destroyOnDelete: false` flag in the State object, after setting it to `true` deletion works just fine 👍

2021-06-02 22:11 UTC, somaritane approved these changes
LGTM 👍

2021-06-02 22:11 UTC, merged