Add support for imagePullSecrets into helm chart
AbsaOSS/terraform-controller pull request #47
Opened 2021-06-04 10:52 UTC by somaritane

Add support for imagePullSecrets into terraform-controller helm chart:

```yaml
# values.yaml:
global:
  imagePullSecrets:
  # list of image pull secrets alike to specified in a pod or service account spec
  - name: regred
```

Signed-off-by: Timofey Ilinykh <timofey.ilinykh@absa.africa>

2021-06-04 11:06 UTC, k0da requested changes
I don't think it is worth to set particular cred into global chart values

2021-06-04 12:58 UTC, somaritane commented
> I don't think it is worth to set particular cred into global chart values

I've got inspired by https://github.com/k8gb-io/k8gb/blob/master/chart/k8gb/templates/service_account.yaml here :) 
When you add imagePullSecrets to a ServiceAccount, that affects all the images deployed by that ServiceAccount, hence I thought it also makes sense to put them to the `global` section in values.yaml.
But I don't have a strong opinion about this, can move them under the `image:` section.

2021-06-04 13:09 UTC, k0da approved these changes, later dismissed
Sorry, my bad. 

Was confused by initial comment. I had an impression you going to put regcred into values.yaml

LGTM

2021-06-04 14:17 UTC, k0da submitted a review, later dismissed

2021-06-07 10:56 UTC, k0da approved these changes

2021-06-07 10:57 UTC, merged